services:
  backend:
    build: 
      context: ./backend_dotnet
    container_name: grocer-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080

  frontend:
    build:
      context: ./frontend-angular
    container_name: grocer-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
